myshop/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path("add/<int:product_id>/",views.add_cart,name="add_cart"),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.cart_delete,name='cart_delete')
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myshop/',include('myshopapp.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cart/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/myshopapp/urls.py
from . import views
from django.urls import path
app_name='myshopapp'
urlpatterns = [
    path('',views.prodcat,name='prodcat'),
    path('<slug:c_slug>/',views.prodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.productDetail, name='productDetail')
]

myshop/searchapp/urls.py
from  django.urls import path
from . import views
app_name='searchapp'
urlpatterns=[

    path('',views.searchresult,name='searchresult')
]

myshop/cart/models.py
from django.db import models
from myshopapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date']
    def __str__(self):
        return  '{}'.format(self.cart_id)
class CartItem(models.Model):
        product=models.ForeignKey(Product,on_delete=models.CASCADE)
        cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
        quantity=models.IntegerField()
        active=models.BooleanField(default=True)
        class Meta:
            db_table='CartItem'
        def sub_total(self):
            return self.product.price * self.quantity

        def __str__(self):
            return '{}'.format(self.product)

myshop/myshopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='categoryimage',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('myshopapp:products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='productimage', blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('myshopapp:productDetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from myshopapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
           cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def cart_delete(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

myshop/myshopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def prodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})
def productDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

myshop/searchapp/views.py
from django.shortcuts import render
from myshopapp.models import Product
from django.db.models import Q
# Create your views here.
def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

myshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"  crossorigin="anonymous">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/f89efd56f0.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>

{% include 'footer.html' %}
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

myshop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   cart page
{% endblock %}
{% block title %}
  cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center">your cart is empty</h1><br>
        <p class="  text-center"> <a class="btn btn-primary" href="{% url 'myshopapp:prodcat' %} ">back</a></p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center">your cart </h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table mytable">
            <thead class="thead">
                <tr>
                    <th colspan="5">your items</th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}<br>
                    SKU:{{cart_item.product.id}}<br>
                    Price:$ {{cart_item.product.price}}<br>
                    Quantity:{{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="cart_icon"><i class="fa fa-plus"></i></a><br>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="cart_icon"><i class="fa fa-minus"></i></a><br>
                    <a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="cart_icon"><i class="fa fa-trash"></i></a>
                </td>
                {% else %}
                 <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="cart_icon"><i class="fa fa-minus"></i></a>
                    <a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="cart_icon"><i class="fa fa-trash"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table  mytable">
        <thead class="thead">
        <tr>
            <th>
                check out
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                review items
            </td>
        </tr>
        <tr>
            <td class="">
                total amount:<strong>{{total}}</strong>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'myshopapp:prodcat' %}" class="btn btn-secondary btn-black mybtn">continue shoping</a>
    </div>

</div>
</div>
{% endif %}
{% endblock %}

myshop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155}}
   {% else %}
      welcome
   {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
      {{ category.name}}-myshop
   {% else %}
     explore
   {% endif %}
{% endblock %}
{% block content %}
   {% if category %}
      <div>
         <div class="row my_row">
            <div class="mx-auto">
               <p><a href="{% url 'myshopapp:prodcat' %}"> our collections</a></p>
            </div>

         </div>
      </div>
   {% endif %}
<div class="mx-auto">
   {% if category %}
   <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div><br>
<div>
   <h1 class="text-center my_title">{{category.name}}</h1>
   <p class="text-justify">{{category.description}}</p>
</div>
   {% else %}
<div>
   <img class="my_image"  src="{% static 'img/newbanner.jpg' %}" alt="our products"  >
</div><br>
<div>
   <h1 class="text-center my_title">our products</h1>
   <p class="text-justify">asdfghjklqwertyuiop</p>
</div>
    {% endif %}
<div class="container">
   <div class="row mx_auto">
      {% for product in products.object_list %}
      <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
         <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top prod_img" src="{{product.image.url}}" alt="{{product.name}}"></a>

           <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
           </div>
         </div>
      </div>
      {% endfor %}
   </div>
   <div class="mx-auto">
      {% if products.paginator.num_pages > 1 %}

      <hr>
      <div class="text-center">
         {% for pg in products.paginator.page_range %}
             <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
         {% endfor %}
      </div>
      {% endif %}
   </div>
   <br>
</div>

{% endblock %}

myshop/templates/footer.html
<footer class="footer footer-fix-bottom">
    <div class="text-center">
        <p >
            @copy;myshop.All rights reserved
        </p>
    </div>
</footer>

myshop/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'myshopapp:prodcat' %}"> <img src="{% static 'img/logo.jpg' %}" alt="logo" width="100px"></a>
    </center>
</header>

myshop/templates/navbar.html
<nav class="navbar  navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown {% if 'myshopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'myshopapp:prodcat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a></li>
            <li><hr class="dropdown-divider"></li>
              {% endfor %}
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

myshop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {{ product.description|truncatewords:155}}
{% endblock %}
{% block title %}
   {% if category %}
      {{ product.name}}-myshop
   {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod">
    <div class="mx_auto">
        <p><a href="{% url 'myshopapp:prodcat' %}">Home</a> | <a href="{{ product.category.get_url}}">{{product.category}}</a> | {{ product.name}}</p>
    </div>

<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12  col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="prod_name">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p>Product Description</p>
            <p class="text-justify">{{product.description}}</p>
            {% if product.stock <= 0 %}
              <p class="out_stock"><b>out of stock</b></p>
            {% else %}
            <a  class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
             </div>

        </div>
</div>
</div>
</div>


{% endblock %}

myshop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   we have variety of products
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
<div>
    <p class=" text-center search"> results for <b>"{{query}}"</b></p>
</div>
<div class="container">
   <div class="row mx_auto">
      {% for product in products %}
      <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
         <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top prod_img" src="{{product.image.url}}" alt="{{product.name}}"></a>

           <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
           </div>
         </div>
      </div>
      {% empty %}
       <div class="row mx-auto">
           <p class="text-center search">no result found</p>
       </div>
       {% endfor %}
   </div>
</div>

{% endblock %}