movieproject/credentials/urls.py
from . import views
from django.urls import path
app_name='credentials'
urlpatterns = [

    path('register', views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('profile',views.profile,name='profile')

]

movieproject/movieapp/urls.py
from . import  views
from django.urls import path
app_name='movieapp'
urlpatterns = [
   path('',views.index,name='index'),
   path('movie/<int:movie_id>/',views.detail,name='detail'),
   path('add/',views.add,name='add'),
   path('update/<int:id>/',views.update,name='update'),
   path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/searchapp/urls.py
from  django.urls import path
from . import views
app_name='searchapp'
urlpatterns=[

    path('result',views.searchresult,name='searchresult')
]

movieproject/credentials/models.py
from django.db import models

# Create your models here.

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/searchapp/models.py
from django.db import models

# Create your models here.

movieproject/movieapp/forms.py
from django import forms
from .models import movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'invalid credentials')
            return redirect('credentials:login')
    return render(request, 'login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username already exists')
                return redirect('credentials:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'email already exists')
                return redirect('credentials:register')
            else:
                user = User.objects.create_user(username=username, password=password, first_name=first_name,
                                                last_name=last_name, email=email)
                user.save();
                return redirect('credentials:login')

        else:
            messages.info(request, 'password not matched')
            return redirect('credentials:register')
        print('user created')
        return redirect('/')

    return render(request, 'register.html')


def logout(request):
    auth.logout(request)
    return redirect('/')


def profile(request):
    if request.user.is_authenticated:
        return render(request, 'profile.html')

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from .forms import MovieForm
# Create your views here.
def index(request):
    details = movie.objects.all()
    context={
        'movielist':details
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    id=movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'id':id})
def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        item=movie(name=name,desc=desc,year=year,img=img)
        item.save()
        return redirect('/')

    return render(request,'add.html')
def update(request,id):
    id=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=id)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'id':id})
def delete(request,id):
    if request.method=='POST':
        id=movie.objects.get(id=id)
        id.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/searchapp/views.py
from django.shortcuts import render
from movieapp.models import Movies,Category
from django.db.models import Q
# Create your views here.
def searchresult(request):
    categories = Category.objects.all()

    movies=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        movies=Movies.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        category=Category.objects.all().filter(Q(name__contains=query))
        return render(request,'search.html',{'query':query,'movies':movies,'category':category,'categories':categories})

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name"placeholder="enter movie name" id="">
  <input type="text" name="desc"placeholder="enter description" id="">
  <input type="number" name="year"placeholder="enter year" id="">
  <input type="file" name="img" placeholder="choose file" id="">
  <input type="submit" value="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">movie store</span>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="post">
    {% csrf_token %}
      are you sure want to delete?
      <input type="submit" value="yes">
</form>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <img src="{{id.img.url}}" alt=""width="350px" height="400px">
    </div>
    <div class="col-md-6">
        <h1>{{id.name}}</h1>
        <h3>{{id.desc}}</h3>
        <h4>{{id.year}}</h4>
        <a class="btn btn-warning" href="{% url 'movieapp:update' id.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' id.id %}">delete</a>
    </div>
   </div>

</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
         {% for i in movielist %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" class="card-img-top" alt="..." width="250px" height="250px">
                    <div class="card-body">
                       <h5 class="card-title">{{i.name}}</h5>
                       <p class="card-text">{{i.desc}}</p>
                       <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">details</a>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

movieproject/templates/moviegrid.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">

<!-- moviegrid07:29-->
<head>
	<!-- Basic need -->
	<title>Open Pediatrics</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href="{% static 'http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' %}" />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->
	<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<!--preloading-->
<div id="preloader">
    <img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>
<!--end of preloading-->

<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="index-2.html"><img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a  href="{% url 'movieapp:index' %}" >
							Home <i class="" aria-hidden="true"></i>
							</a>

						</li>
						<li class="dropdown first">
							<a   href="{% url 'movieapp:allmovie' %}"  data-hover="dropdown">
							All movies<i class="" aria-hidden="true"></i>
							</a>

						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown">
							Categories <i class="fa fa-angle-down" aria-hidden="true"></i>
							</a>
							<ul class="dropdown-menu level1">
								{% for i in categories %}
								<li><a href="{% url 'movieapp:allmovie' %}?i={{ i.name }}">{{i.name}}</a></li>
								{% endfor %}

							</ul>
						</li>



					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">

						{% if user.is_authenticated %}
						<li><a href="{% url 'movieapp:addmovie' %}">Add Movie</a></li>
						<li ><a href="{% url 'credentials:profile' %}"><h4 style="color:red;font-weight:bold;">{{user.username}}</h4></a></li>
						<li><a href="{% url 'credentials:logout' %}">Logout</a></li>
						{% else %}
						<li ><a href="{% url 'credentials:login' %}">LOG In</a></li>
						<li ><a href="{% url 'credentials:register' %}">sign up</a></li>
						{% endif %}
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	    
	    <!-- top search form -->
	    <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
		   <div class="row">
			   <div class="col-md-11">
				   <input class="form-control me-2" type="search" placeholder="Search your movies here" name="q" aria-label="Search">
			   </div>
			   <div class="col-md-1">
				   <button class="btn btn-outline-success" type="submit"><i class="ion-android-search"></i></button>
			   </div>
		   </div>
		</form>
	</div>
</header>
<!-- END | Header -->

<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">

					{% if category %}
					<h1>{{category}}</h1>
					{% else %}
					<h1>All Movies</h1>
					{% endif %}
					<ul class="breadcumb">
						<li class="active"><a href="{% url 'movieapp:index' %}">Home</a></li>
						{% if category %}
						<li> <span class="ion-ios-arrow-right"></span>{{category.name}}</li>
						{% else %}
						<li> <span class="ion-ios-arrow-right"></span>All Movies</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-12 col-sm-12 col-xs-12 ">

				<div class="flex-wrap-movielist">
					    {% for movie in movies %}
						<div class="movie-item-style-2 movie-item-style-1">
							<img src="{{movie.img.url}}" alt="">
							<div class="hvr-inner">
	            				<a  href="{% url 'movieapp:moviedetail' movie.id  %}"> Read more <i class="ion-android-arrow-dropright"></i> </a>
	            			</div>
							<div class="mv-item-infor">
								<h6><a href="#">{{movie.name}}</a></h6>
								<p>{{movie.category}}</p>

							</div>
						</div>
					    {% endfor %}

				</div>		
				<div class="topbar-filter">
					<label>Movies per page:12 Movies</label>


					<div class="pagination2">
						{% if products.paginator.num_pages > 1 %}
						{% for pg in products.paginator.page_range %}
            		 	<a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
         			    {% endfor %}
						{% endif %}
					</div>
				</div>
			</div>


		</div>
	</div>
</div>
<!-- footer section-->
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href=""><img class="logo" src="{% static 'images/logo1.png' %}" alt=""></a>

			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="#">About</a></li> 
					<li><a href="#">Blockbuster</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Forums</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Help Center</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Legal</h4>
				<ul>
					<li><a href="#">Terms of Use</a></li> 
					<li><a href="#">Privacy Policy</a></li>	
					<li><a href="#">Security</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
					<li><a href="#">My Account</a></li> 
					<li><a href="#">Watchlist</a></li>	
					<li><a href="#">Collections</a></li>
					<li><a href="#">User Guide</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">

		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>
<!-- end of footer section-->

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/plugins2.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

<!-- moviegrid07:38-->
</html>

movieproject/templates/moviesingle.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">

<!-- moviesingle07:38-->
<head>
	<!-- Basic need -->
	<title>Open Pediatrics</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href="{% static 'http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' %}" />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->
	<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<!--preloading-->
<div id="preloader">
    <img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>
<!--end of preloading-->


<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href=""><img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a  href="{% url 'movieapp:index' %}" >
							Home <i class="" aria-hidden="true"></i>
							</a>

						</li>
						<li class="dropdown first">
							<a   href="{% url 'movieapp:allmovie' %}"  data-hover="dropdown">
							All movies<i class="" aria-hidden="true"></i>
							</a>

						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown">
							Categories <i class="fa fa-angle-down" aria-hidden="true"></i>
							</a>
							<ul class="dropdown-menu level1">
								{% for i in categories %}
								<li><a href="{% url 'movieapp:allmovie' %}?i={{ i.name }}">{{i.name}}</a></li>
								{% endfor %}

							</ul>
						</li>



					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">

						{% if user.is_authenticated %}
						<li><a href="{% url 'movieapp:addmovie' %}">Add Movie</a></li>
						<li ><a href="{% url 'credentials:profile' %}"><h4 style="color:red;font-weight:bold;">{{user.username}}</h4></a></li>
						<li><a href="{% url 'credentials:logout' %}">Logout</a></li>
						{% else %}
						<li ><a href="{% url 'credentials:login' %}">LOG In</a></li>
						<li ><a href="{% url 'credentials:register' %}">sign up</a></li>
						{% endif %}
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	    
	    <!-- top search form -->
	    <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
		   <div class="row">
			   <div class="col-md-11">
				   <input class="form-control me-2" type="search" placeholder="Search your movies here" name="q" aria-label="Search">
			   </div>
			   <div class="col-md-1">
				   <button class="btn btn-outline-success" type="submit"><i class="ion-android-search"></i></button>
			   </div>
		   </div>
		</form>
	</div>
</header>
<!-- END | Header -->
<div class="hero mv-single-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- <h1> movie listing - list</h1>
				<ul class="breadcumb">
					<li class="active"><a href="#">Home</a></li>
					<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>

<div class="page-single movie-single movie_single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="movie-img sticky-sb">
					<img src="{{movie.img.url}}" alt="">
					<div class="movie-btn">	
						<div class="btn-transform  red">
							<div><a href="{% url 'movieapp:updatemovie' movie.id  %}" class="item item-1 yellowbtn"> Update</a></div>

						</div>
						<div class="btn-transform ">
							<div><a href="{% url 'movieapp:deletemovie' movie.id  %}" class="item item-1 redbtn"> </i> Delete</a></div>

						</div>
					</div>
				</div>
			</div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="movie-single-ct main-content">
					<h1 class="bd-hd">{{movie.name}}</h1>
					<div class="social-btn">
						<a href="#" class="parent-btn"><i class="ion-heart"></i> Add to Favorite</a>
						<div class="hover-bnt">
							<a href="#" class="parent-btn"><i class="ion-android-share-alt"></i>share</a>
							<div class="hvr-item">
								<a href="#" class="hvr-grow"><i class="ion-social-facebook"></i></a>
								<a href="#" class="hvr-grow"><i class="ion-social-twitter"></i></a>
								<a href="#" class="hvr-grow"><i class="ion-social-googleplus"></i></a>
								<a href="#" class="hvr-grow"><i class="ion-social-youtube"></i></a>
							</div>
						</div>		
					</div>


					<div class="movie-tabs">
						<div class="tabs">
							<ul class="tab-links tabs-mv">
								<li class="active"><a href="#overview">Overview</a></li>

							</ul>
						    <div class="tab-content">
						        <div id="overview" class="tab active">
						            <div class="row">
						            	<div class="col-md-8 col-sm-12 col-xs-12">

                                            <div class="title-hd-sm">
												<h4>Movie Name : {{movie.name}}</h4>
											</div>

											<div class="title-hd-sm">
												<h4>Category : {{movie.category}}</h4>

											</div>
											<div class="title-hd-sm">
												<h4>Description : {{movie.description}}</h4>

											</div>
											<div class="title-hd-sm">
												<h4>Release Date : {{movie.releasedate}}</h4>

											</div>
											<div class="title-hd-sm">
												<h4>Actors : {{movie.actors}}</h4>

											</div>
											<div class="title-hd-sm">
												<h4>Trailer Link : {{movie.trailerlink}}</h4>

											</div>
						            	</div>

						            </div>
						        </div>

						    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- footer section-->
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href=""><img class="logo" src="{% static 'images/logo1.png' %}" alt=""></a>

			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="#">About</a></li>
					<li><a href="#">Blockbuster</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Forums</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Help Center</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Legal</h4>
				<ul>
					<li><a href="#">Terms of Use</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Security</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
					<li><a href="#">My Account</a></li>
					<li><a href="#">Watchlist</a></li>
					<li><a href="#">Collections</a></li>
					<li><a href="#">User Guide</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">

		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>
<!-- end of footer section-->

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/plugins2.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

<!-- moviesingle11:03-->
</html>

movieproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<!-- Coding by CodingLab | www.codinglabweb.com-->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration or Sign Up form in HTML CSS | CodingLab </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
   </head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
    <form action="register" method="post">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" name="username" placeholder="Enter user name" required>
      </div>
      <div class="input-box">
        <input type="text" name="first_name" placeholder="Enter first name" required>
      </div>
      <div class="input-box">
        <input type="text" name="last_name" placeholder="Enter last name" required>
      </div>
      <div class="input-box">
        <input type="email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <input type="password" name="password" placeholder="Create password" required>
      </div>
      <div class="input-box">
        <input type="password" name="cpassword" placeholder="Confirm password" required>
      </div>
      <div class="policy">
        <input type="checkbox">
        <h3>I accept all terms & condition</h3>
      </div>
      <div class="input-box button">
        <input type="Submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="loginnow">Login now</a></h3>
      </div>
    </form>
    {% for i in messages %}
    {{i}}
    {% endfor %}
  </div>

</body>
</html>